### ISSUE TITLE
Paid DE localizer: ID, get contract, and confirm budget

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#348]
Option: http://www.kontextor.org/en/ (used by Firefox brand and marketing teams)
For urgent translation / localization, Wikimedia utilizes a paid translator who can provide rapid, more agile support. 

**Background**
We have a number of localization and translation needs as we expand our non-EN fundraising strategies. 
* L10N needs a ~3-week window in which to localize content
* For text we have ~3 weeks in advance, utilize L10N for initial localization
* For text that is outside the window for L10N support, we need a paid translator or translation service.
* Anything translated or localized by the service will be presented to L10N for quick review / approval

**Tasks:**
- [ ] Select a service or individual contractor for DE
- [ ] Accounting approval (budget confirmed)
- [ ] Sign contract
- [ ] Alert L10N and confirm process for submitting translations for quick review (<24 hrs)

cc @alicoding

**Comment by valianttry** [comment]
I am setting up a meeting with Grigorios from Kontextor. See email below.


On Mon, Aug 31, 2015 at 12:49 PM, Grigorios Petsos <Grigorios@kontextor.ie> wrote:

Hi Andrea,

regarding your offer to engage us perhaps for other projects, here are our standard rates:
 

·        0,22 Euro per word for translations

·        60 Euro hourly rate for language support that can't be measured in words, e.g. reviews, QA, audits, linguistic consulting etc.

·        90 Euro hourly rate for project management (if you would like us to manage whole projects for you)

 

The rates apply for all of the more than 25 languages we support. Amongst these are nearly all European languages, but also the most important Asian ones.

 

To give you an exact estimation, we would need a project description.

 

We can also have a call this and to discuss options.

 

Let me know how you would like to proceed.

 

All the best

 

Grigorios

cid:0527C7CE-2774-435B-8FE4-3839EFB845C2

Grigorios Petsos

kontextor teoranta

info@kontextor.ie

+49 (0)177 428 28 51

www.kontextor.com

 

Office  Ireland

Century House, Harold's Cross Road, Dublin 6w, Dublin Co. Dublin

 

Office Germany

Paul-Lincke-Ufer 20-22; 10999 Berlin

 

Company Registration Number: 488429

Registergericht Deutschland: Amtsgericht Charlottenburg

Register und Registernummer: HRB 129801 B

USt-ID-Nr.: DE273843733

Director/Geschäftsführer: Grigorios Petsos

**Comment by valianttry** [comment]
We will be launching a contract with Kontextor -- and they need some info to fire up our contract process:

·        How many words per language or strings per week do you appoximately expect? Will the translation requests arrive daily?

·        Are we talking about a translation or a localization/adaption?

·        We normally use word counts to calculate the efforts. As this is not automatically possible in Pantoon, we could also agree on an hourly basis payment. What do you think?

·        Our standard procedure with other customers includes an assignment in the morning with all information what needs to be done during the day. Would that be a procedure that would work for you, too?
(As we are based in Europe we could work while you sleep.)

·        Are there additional/included tasks or steps that you expect/wish us to do (apart from the pure translation)?

@alicoding do you want to take a first stab at estimating words by target locale?

**Comment by edrushka** [comment]
when it's time, contract details get filed according to [this] (https://mana.mozilla.org/wiki/display/FOUNDATION/Independent+Contractors)

**Comment by valianttry** [comment]
Contract for Kontextor is underway in this Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1205044

**Comment by valianttry** [comment]
Contract countersigned -- confirmed.
