### ISSUE TITLE
Ship it

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#492]
A ticket to document and track the steps (and order) of tasks for shipping the new donation pages.

- [x] Setup Stripe Account (All)
- [x] Setup / Update all environment variables on production hosting (@jbuck)
- [x] Deploy project to donate.mofoprod.net (Any Engineer)
- [x] [Close P1s](https://github.com/mozilla/donate.mozilla.org/milestones/New%20Fundraising%20Platform%20Launch)
- [x] Run through [QA checklist](https://github.com/mozilla/donate.mozilla.org/blob/master/docs/QA_Checklist.md) on production (All)
- [x] [Update DNS for donate.mozilla.org](https://bugzilla.mozilla.org/show_bug.cgi?id=1221736) to point to new server (@jbuck)
- [x] Setup / Update all server monitoring (@jbuck)
- [x] Switch to new DE snippet (euros version), which sends donors to donate.mozilla.org (Fundraising Team in collaboration with MoCo team)
- [x] [Update any external links to BSD donation forms at source](https://github.com/mozilla/donate.mozilla.org/issues/740) (e.g. @valianttry work with MoCo to update mozilla.org and tabzilla links)
- [x] [Monitor for several days](https://github.com/mozilla/donate.mozilla.org/issues/738) (@jbuck @adamlofting)
- [x] Once happy with performance, [setup front end redirects on all live BSD donation forms](https://github.com/mozilla/donate.mozilla.org/issues/739) to send traffic to new donate.m.o forms (Engineers)

cc @valianttry @edrushka @alicoding @jbuck @ScottDowne

**Comment by valianttry** [comment]
@adamlofting can you provide details about what we need to communicate to MoCo about the donation forms and URLs? I anticipate they'll want to know what the UX will be like, for what locales, and what exactly we're changing.

**Comment by adamlofting** [comment]
> @adamlofting can you provide details about what we need to communicate to MoCo about the donation forms and URLs? I anticipate they'll want to know what the UX will be like, for what locales, and what exactly we're changing.

The short version is that anywhere we're currently linking to a BSD form from a MoCo managed property, we'll want to update the link to point to the equivilent page on our new forms. The UX will be equivilent to the existing BSD flow, but hosted on our new pages. 

Is there an existing list from when we've setup these links in the past?

**Comment by valianttry** [comment]
@adamlofting we met with the mozilla.org team incl. @bniolet1, Jen Bertsch, and Jenny Douglas and they are ready to receive those links when we have them ready. It does take some time to update all of them, so ideally we would get them to Jen soon -- in the next week or 10 days possible? I will ask Jen if there is an existing list -- or I'll look up past bugs we filed to update links. We are also adding new donate links to Mozilla.org in some locales where we previously didn't accept currencies also, I believe. I teed that up as well and they are ready.

**Comment by adamlofting** [comment]
That's great :+1: 

>  It does take some time to update all of them, so ideally we would get them to Jen soon -- in the next week or 10 days possible?

This task doesn't need to happen until we've worked through the rest, and it's not a problem if it takes 10+ days after that. We'll have 'front-end' redirects on the old forms anyway, but this is a good excercise in cleaning up the links before we switch off BSD.

**Comment by valianttry** [comment]
I created https://github.com/mozilla/donate.mozilla.org/issues/545 to manage the new URL task.

**Comment by jbuck** [comment]
IT'S SHIPPED :tada: :tada: :tada: 

I filed follow-up tasks in the new milestone

**Comment by adamlofting** [comment]
:hatching_chick: :hatched_chick: :baby_chick: :chicken: :money_with_wings:

**Comment by ScottDowne** [comment]
:heart: :tangerine: :moneybag: :four_leaf_clover: :new_moon: :crystal_ball: :hibiscus:
