### ISSUE TITLE
take another pass at the qa checklist

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#515]
Initially I'm just going to do a brain dump of all the things we need tested.

Yes, all, I want this complete. Every possible thing donate can do and all the fringe cases.

**Comment by ScottDowne** [comment]
Paypal
- variables: frequency, locale, currency, and amount.
- test creds: send-donation@test.com:testtest
 - [ ] check that the log in page has the correct amount and currency, try different variations.
 - [ ] if monthly, ensure it's stated on the log in page.
 - [ ] log in page should match your locale (this likely needs to be done in a private tab, or it'll be in the locale that you last logged in with)
 - [ ] after logging in, ensure you're in your account's locale, and not the original locale.
 - [ ] after donating, ensure you're immediately redirected to thank you page
 - [ ] check that thank-you page has query string params like this "?frequency=single&tx=7B421206T6081912R&amt=3.00&cc=USD" should match your initial donation.
 - [ ] check that the thank you page locale matches your original locale.

**Comment by ScottDowne** [comment]
Query string
- todo

**Comment by ScottDowne** [comment]
stripe
- todo

**Comment by ScottDowne** [comment]
locales
- todo

**Comment by ScottDowne** [comment]
signup
- todo

**Comment by ScottDowne** [comment]
components
- todo

**Comment by ScottDowne** [comment]
currency
- todo

**Comment by ScottDowne** [comment]
stripe errors
- todo

**Comment by ScottDowne** [comment]
metrics
- todo

**Comment by ScottDowne** [comment]
available pages
- todo

**Comment by ScottDowne** [comment]
share
- todo

**Comment by ScottDowne** [comment]
redirects
- todo

**Comment by adamlofting** [comment]
Quick note from conversation on our call just now.

When QA'ing analytics. I check the donation thank you page for requests made to Optimizely and GA in the network view of the developer tools. The donation amounts / product names etc should be passed as query parameters.

I'll also use the GA real-time report to look at the 'Staging' filter for donate.mofostaging.net to check the correct transactions are being recorded.
